spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery
          lowerCaseServiceId: true
      routes:
        - id: accounts-route-1
          uri: lb://ACCOUNTS  # Load balance to the "accounts" service registered with Eureka
          predicates:
            - Path=/ivr/**  # Route requests with /accounts/** path to the "accounts" service
          filters:
            - AuthenticationFilter
            # Add more predicates as needed for your routing requirements
        - id: accounts-route-2
          uri: lb://ACCOUNTS  # Load balance to the "accounts" service registered with Eureka
          predicates:
            - Path=/ivr/cards/**
          filters:
            - AuthenticationFilter

        - id: securityapplication-route
          uri: lb://SECURITYAPPLICATION  # Load balance to the "security" service registered with Eureka
          predicates:
            - Path=/auth/**



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      gatewayserver:
        com: DEBUG
server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"